version: "3.8"

services:
  rune-js-server:
    image: node:14
    container_name: server
    ports:
      - "43594:43594"
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start

networks:
  default:
    name: rune_js_network
